import React from 'react';
import { motion } from 'framer-motion';
import { Share2, Download, Copy, Check, FileSearch } from 'lucide-react';
import { AnalysisResponse } from '../types/analysis';
import { VerdictCard } from './VerdictCard';
import { MisleadingElements } from './MisleadingElements';
import { ExplanationCard } from './ExplanationCard';
import { FactCheckCard } from './FactCheckCard';
import { SourcesCard } from './SourcesCard';
import { ClaimBreakdown } from './ClaimBreakdown';

interface ResultDashboardProps {
  result: AnalysisResponse;
  originalText: string;
}

export const ResultDashboard: React.FC<ResultDashboardProps> = ({ result, originalText }) => {
  const [copied, setCopied] = React.useState(false);

  // Fallbacks for older cached items
  const verdictText = result.result || result.verdict || "ERROR";
  const confidence = result.confidence || 0;
  const factCheckingText = result.evidence && result.evidence.length > 0 
    ? result.evidence.map(e => `- ${e}`).join('\n') 
    : (result.fact_checking || "No verification available.");

  const handleCopy = () => {
    const textToCopy = `TruthScan AI Analysis\n\nResult: ${verdictText} (${confidence}%)\n\nExplanation:\n${result.explanation}\n\nVerification:\n${factCheckingText}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = `TRUTHSCAN AI REPORT
====================

RESULT: ${verdictText}
CONFIDENCE: ${confidence}%

${result.title ? `TITLE: ${result.title}\n` : ''}${result.source ? `SOURCE: ${result.source}\n` : ''}
ORIGINAL/EXTRACTED TEXT:
${result.extracted_text || originalText}

AI EXPLANATION:
${result.explanation}

VERIFICATION:
${factCheckingText}

Generated by TruthScan AI
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TruthScan_Report_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'TruthScan AI Analysis',
          text: `I just analyzed a news story using TruthScan AI. The result was: ${verdictText}.`,
        });
      } catch (err) {
        console.error("Share failed", err);
      }
    } else {
      handleCopy();
    }
  };

  return (
    <section className="w-full h-full pb-12 z-20">
      <div className="flex flex-col gap-6">
        <VerdictCard result={verdictText as any} confidence={confidence} />
        
        {/* Extracted Context Card for URLs and Images */}
        {(result.title || result.source || result.extracted_text) && (
          <div className="glass-panel rounded-2xl p-6 border-l-4 border-l-accent">
            <div className="flex items-center gap-2 mb-4">
              <FileSearch className="w-5 h-5 text-accent" />
              <h3 className="font-bold text-white">Extracted Context</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
              {result.source && (
                <div>
                  <span className="text-[10px] uppercase tracking-wider text-gray-500 font-bold block mb-1">Source</span>
                  <span className="text-sm font-medium text-gray-300">{result.source}</span>
                </div>
              )}
              {result.title && (
                <div>
                  <span className="text-[10px] uppercase tracking-wider text-gray-500 font-bold block mb-1">Title</span>
                  <span className="text-sm font-medium text-gray-300">{result.title}</span>
                </div>
              )}
            </div>
            {result.extracted_text && (
              <div>
                <span className="text-[10px] uppercase tracking-wider text-gray-500 font-bold block mb-2">Detected Text snippet</span>
                <div className="bg-black/40 rounded-lg p-3 max-h-32 overflow-y-auto custom-scrollbar">
                  <p className="text-xs text-gray-400 font-mono italic">"{result.extracted_text.substring(0, 300)}{result.extracted_text.length > 300 ? '...' : ''}"</p>
                </div>
              </div>
            )}
          </div>
        )}

        {result.claims && result.claims.length > 0 && (
          <ClaimBreakdown claims={result.claims} />
        )}

        {(result.misleading_elements && result.misleading_elements.length > 0) && (
          <MisleadingElements elements={result.misleading_elements} />
        )}
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <ExplanationCard explanation={result.explanation} />
          <FactCheckCard factChecking={factCheckingText} />
          <SourcesCard sources={result.sources_checked || result.sources || []} />
        </div>

        {/* Actions */}
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="flex flex-wrap justify-end gap-4 mt-2"
        >
          <button onClick={handleCopy} className="flex items-center gap-2 px-4 py-2 rounded-lg glass-button text-gray-300 font-medium hover:text-white transition-colors">
            {copied ? <Check className="w-4 h-4 text-success" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy Results'}
          </button>
          
          <button onClick={handleDownload} className="flex items-center gap-2 px-4 py-2 rounded-lg glass-button text-gray-300 font-medium hover:text-white transition-colors">
            <Download className="w-4 h-4" />
            Download Report
          </button>

          <button onClick={handleShare} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-accent/20 text-accent hover:bg-accent/30 border border-accent/30 transition-all font-medium">
            <Share2 className="w-4 h-4" />
            Share
          </button>
        </motion.div>
      </div>
    </section>
  );
};
